#Advanced Indexing

In [1]:
import numpy as np

In [2]:
arr=np.array([10,20,30,40,50,60])
print(arr[(arr>20)&(arr<50)])


[30 40]


In [3]:
arr[arr>30]=0
print(arr)

[10 20 30  0  0  0]


In [6]:
arr=np.array([21,22,86,45,32,56])
arr[arr%2==0]

array([22, 86, 32, 56])

#Mini Data style Practice

In [21]:
marks=np.array([45,32,98,38,63,23,78])
print("Average of marks : ",np.mean(marks))
print("Highest marks : ",np.max(marks))
print("Lowest marks : ",np.min(marks))
print("Student passed : ",marks[marks>=50])
marks.sort()
print("Top 3 Students : ",marks[-1:-4:-1])
print("Added 5 grace marks to all ",marks+5)
marks[marks>40]=0
print(marks)

Average of marks :  53.857142857142854
Highest marks :  98
Lowest marks :  23
Student passed :  [98 63 78]
Top 3 Students :  [98 78 63]
Added 5 grace marks to all  [ 28  37  43  50  68  83 103]
[23 32 38  0  0  0  0]


#sorting and unique

In [19]:
arr=np.array([5,3,1,2,8,2,5])

print(np.sort(arr))
np.unique(arr)


[1 2 2 3 5 5 8]


array([1, 2, 3, 5, 8])

#DSA

#Longest Substring without Repeating

In [25]:
def longest_substr(s):
    char_set=set()
    left=0
    max_len=0
    for right in range(len(s)):
        while s[right] in char_set:
            char_set.remove(s[left])
            left+=1
        char_set.add(s[right])
        max_len=max(max_len,right-left+1)

    return max_len
string="abbaac"
print(longest_substr(string))
        

2


In [26]:
#Mini Challenge
arr=np.array([10,2,3,4,5,6])
#Replace all > 3 with 0
arr[arr>3]=0
print(arr)

[0 2 3 0 0 0]
