#Advanced Concepts

In [1]:
import numpy as np

In [2]:
#Reshape to 1D -> 2D
arr=np.arange(1,10)
print(arr.reshape(3,3))

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [5]:
#Flatten Matrix 2D -> 1D
arr2=np.array([[1,3,2],[6,7,8],[2,7,3]])
print(arr2.flatten())

[1 3 2 6 7 8 2 7 3]


In [7]:
#Numpy aggrigations 
arr=np.array([10,20,30,40,50,60])

print(np.sum(arr))
print(np.mean(arr))
print(np.min(arr))
print(np.max(arr))
print(np.std(arr))

210
35.0
10
60
17.07825127659933


In [9]:
#2D case

arr3=np.array([[2,3,5],[89,23,67],[23,12,9]])

print(np.sum(arr3,axis=0)) #Column wise 
print(np.sum(arr3,axis=1)) #Row wise

[114  38  81]
[ 10 179  44]


In [10]:
#Broadcasting
print(arr + 10)
print(arr2 + 10)


[20 30 40 50 60 70]
[[11 13 12]
 [16 17 18]
 [12 17 13]]


In [11]:
#Kadane's Algorithm refresh revise without seeying code 

def max_subarray_sum(arr):
    current_sum=arr[0]
    max_sum=current_sum
    for n in arr[1:]:
        current_sum=max(current_sum+n,n)
        max_sum=max(max_sum,current_sum)
    return max_sum

arr=[1,2,9,4,5,-2,3,-7]
print(max_subarray_sum(arr))

22


In [38]:
#Mini Task 
arr4=np.array([1,2,3,4,5,6])

print(arr4[arr4>3]*0)

[0 0 0]
