#Numpy

In [1]:
import numpy as np

In [10]:
a=np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [6]:
b=np.zeros(5)
print(b)

[0. 0. 0. 0. 0.]


In [7]:
c=np.ones(5)
print(c)

[1. 1. 1. 1. 1.]


In [9]:
d=np.arange(1,10)
print(d)

[1 2 3 4 5 6 7 8 9]


#Operations

In [12]:
a+5

array([6, 7, 8, 9])

In [13]:
a-2

array([-1,  0,  1,  2])

In [14]:
a*2

array([2, 4, 6, 8])

In [15]:
a**2

array([ 1,  4,  9, 16])

#Functions

In [16]:
np.sum(a)

np.int64(10)

In [18]:
np.mean(a)

np.float64(2.5)

In [19]:
np.max(a)

np.int64(4)