#Numpy Core Concepts 

In [4]:
#Indexing

import numpy as np
arr=np.array([12,34,65,58,92,23])

print(arr[3])
print(arr[0])
print(arr[-1])
print(arr[-3])

58
12
23
58


#Slicing

In [12]:
print(arr[1:3])
print(arr[:4])
print(arr[::-1])
print(arr[2:5])

[34 65]
[12 34 65 58]
[23 92 58 65 34 12]
[65 58 92]


In [15]:
#2D array Indexing 
matrix=np.array([[2,3,8],[7,1,9]])

print(matrix[0][2])
print(matrix[1][1])

#or 

print(matrix[0,2])
print(matrix[1,1])

8
1
8
1


In [17]:
#boolean Masking
print(arr)

print(arr[arr>25])
print(arr[arr%2==0])

[12 34 65 58 92 23]
[34 65 58 92]
[12 34 58 92]


In [19]:
#Mini Task
arr2=np.array([5,10,15,20,25])

#element greater than 10
print(arr2[arr2>10])

#get only odd numbers
print(arr2[arr2%2!=0])

#multiply elements greater than 15 by 2
print(arr2[arr2>15]*2)


[15 20 25]
[ 5 15 25]
[40 50]
