In [2]:
import numpy as np

In [6]:
myarr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(myarr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [12]:
myarr=np.zeros((3,4))
print(myarr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [15]:
myarr=np.ones((3,4))
print(myarr)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [16]:
myarr=np.full((3,4),6)
print(myarr)

[[6 6 6 6]
 [6 6 6 6]
 [6 6 6 6]]


In [17]:
myarr=np.eye(4)
print(myarr)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [26]:
myarr=np.arange(1,100,5)
print(myarr)

[ 1  6 11 16 21 26 31 36 41 46 51 56 61 66 71 76 81 86 91 96]


In [29]:
myarr=np.linspace(1,100,4)
print(myarr)

[  1.  34.  67. 100.]


In [36]:
myarr=np.full((2,4),5)
print(myarr.shape)
print(myarr.reshape(4,2))
print(myarr.size)
print(myarr.ndim)
print(myarr.dtype)

(2, 4)
[[5 5]
 [5 5]
 [5 5]
 [5 5]]
8
2
int64


In [39]:
myarr=np.array([1,3,2,5,6,7,8,9],dtype=np.float32)
print(myarr)

[1. 3. 2. 5. 6. 7. 8. 9.]


In [41]:
newarr=myarr.astype(np.int32)
print(newarr)
print(newarr.dtype)

[1 3 2 5 6 7 8 9]
int32


In [49]:
new_arr=np.arange(1,100,3)
print(new_arr)
print(new_arr.size)
arr2=new_arr.reshape(3,11)
print(arr2)

[ 1  4  7 10 13 16 19 22 25 28 31 34 37 40 43 46 49 52 55 58 61 64 67 70
 73 76 79 82 85 88 91 94 97]
33
[[ 1  4  7 10 13 16 19 22 25 28 31]
 [34 37 40 43 46 49 52 55 58 61 64]
 [67 70 73 76 79 82 85 88 91 94 97]]


In [51]:
flatted_arr=arr2.flatten()
print(flatted_arr)

[ 1  4  7 10 13 16 19 22 25 28 31 34 37 40 43 46 49 52 55 58 61 64 67 70
 73 76 79 82 85 88 91 94 97]
