#Data types in numpy 
in numpy the default values of int is int64 and for float its float64
we can use int32 and float32 instead for less memory and fast performance 

In [1]:
import numpy as np

In [2]:
arr=np.array([21,23,1,25,34])

In [3]:
arr.dtype

dtype('int64')

In [4]:
arr.astype("float64")

array([21., 23.,  1., 25., 34.])

In [5]:
arr.astype("int32")

array([21, 23,  1, 25, 34], dtype=int32)

In [6]:
arr.astype("float32")

array([21., 23.,  1., 25., 34.], dtype=float32)

In [17]:
arr2=np.array([23,96,8,9,6],dtype="int32")


In [18]:
arr2.dtype

dtype('int32')

In [19]:
arr.nbytes

40

In [20]:
arr2.nbytes

20

In [21]:
arr3=np.array([1+2j,2+3j,4+6j],dtype="complex128")
print(arr3)

[1.+2.j 2.+3.j 4.+6.j]


#Always choose right datatype is very important for optimizing the memory usage.

using smallest datatype which fit the data actually improves the performance.

smaller datatypes actually performs the fast operations so its ensures precision.